# Generated by Django 4.2.7 on 2023-11-23 17:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 17, 7, 33, 871807, tzinfo=datetime.timezone.utc)),
        ),
    ]
