# Generated by Django 4.2.5 on 2023-12-12 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_date_joined_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 12, 13, 57, 51, 178616)),
        ),
    ]
