# Generated by Django 4.1.11 on 2023-12-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palteforme', '0003_assignment_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='studentName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
