# Generated by Django 4.2.7 on 2023-11-22 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('email', models.EmailField(blank=True, max_length=255, null=True, unique=True)),
                ('is_student', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_tutor', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=datetime.timezone)),
            ],
        ),
    ]
