# Generated by Django 5.0.2 on 2024-03-03 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_date_joined_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 3, 15, 58, 27, 705213)),
        ),
    ]
