# Generated by Django 5.0.2 on 2024-02-26 00:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palteforme', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
        migrations.RemoveField(
            model_name='notificationtarget',
            name='additional_field',
        ),
        migrations.AddField(
            model_name='notificationtarget',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 1, 15, 3, 771644)),
        ),
    ]
