# Generated by Django 5.0.2 on 2024-02-26 00:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palteforme', '0003_remove_notification_is_read_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 26, 1, 16, 43, 571048)),
        ),
        migrations.AlterModelTable(
            name='notificationtarget',
            table='notificationtarget',
        ),
    ]
