# Generated by Django 5.0.2 on 2024-02-28 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palteforme', '0004_alter_material_upload_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 28, 21, 6, 31, 844351)),
        ),
    ]
