# Generated by Django 5.0.2 on 2024-02-20 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('palteforme', '0005_verif'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='course',
        ),
        migrations.AlterModelTable(
            name='enrollment',
            table='enrollment',
        ),
    ]
