# Generated by Django 5.0.2 on 2024-02-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palteforme', '0006_alter_course_table_alter_enrollment_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=1, upload_to='courseImages/'),
            preserve_default=False,
        ),
    ]
