# Generated by Django 5.0.2 on 2024-02-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palteforme', '0007_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='course',
        ),
        migrations.AlterModelTable(
            name='assignment',
            table='assignment',
        ),
        migrations.AlterModelTable(
            name='grade',
            table='grade',
        ),
        migrations.AlterModelTable(
            name='interactionhistory',
            table='interactionHistory',
        ),
        migrations.AlterModelTable(
            name='material',
            table='material',
        ),
        migrations.AlterModelTable(
            name='readingstate',
            table='readingState',
        ),
        migrations.AlterModelTable(
            name='submission',
            table='submission',
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='palteforme.course')),
            ],
            options={
                'db_table': 'lesson',
            },
        ),
        migrations.AddField(
            model_name='material',
            name='lesson',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='palteforme.lesson'),
            preserve_default=False,
        ),
    ]
