# Generated by Django 5.0.2 on 2024-02-21 23:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('palteforme', '0008_remove_material_course_alter_assignment_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='upload_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 22, 0, 29, 3, 107179)),
        ),
    ]
